### ISSUE TITLE
Crash / Access violation

### ISSUE THREAD

**Issue by ilko-k** [HomeOfVapourSynthEvolution/VSFilterMod#3]
This occurs when vector shapes are re-sampled (so coordinate values get floating point). Not sure what exactly causes the crash, but it seems to happen if there are more than one bezier curve.

How to reproduce : 

1. Launch Aegisub
2. Load a dummy video in HD 720p
3. Copy-paste `{\p1}m -1 42 l 200 42 b 133 -44 330 27 -1 42 m 200 42 l -1 42 b 66 128 -131 57 200 42` in the default line
4. Load a dummy video again but this time in FHD 1080p
5. Resample resolution from source (720p) to new (1080p)

Watch the video : https://youtu.be/PvTTnUgobi4

**Comment by HolyWu** [comment]
Sorry, this repo is no longer maintained. The successor is https://github.com/sorayuki/VSFilterMod. The floating point crash bug is also fixed. You can download the compiled dlls from the attachment of https://www.nmm-hd.org/newbbs/viewtopic.php?f=17&t=1989.
