### ISSUE TITLE
floating-point vectors not displaying

### ISSUE THREAD

**Issue by sneaker2** [HomeOfVapourSynthEvolution/VSFilterMod#4]
Hi,

there is a user report about ASS vectors not displaying with VSFilterMod but working fine with (xy-)vsfilter and assrender. Sample attached.

[blue_test.zip](https://github.com/HomeOfVapourSynthEvolution/VSFilterMod/files/1614932/blue_test.zip)

 For reference:
https://forum.videohelp.com/threads/369913-StaxRip-support-thread/page8#post2507411
https://forum.doom9.org/showthread.php?p=1829817

**Comment by HolyWu** [comment]
I tried opening the sample in Aegisub with both xy-vsfilter and libass. All I get is simply a blue rectangle like [this](https://imgur.com/De1Y8QS).

**Comment by sneaker2** [comment]
Yes. that's how it is supposed to look from what I can tell. VSFilterMod doesn't display that rectangle.

**Comment by HolyWu** [comment]
OK I see. The issue is quite the same as https://github.com/HomeOfVapourSynthEvolution/VSFilterMod/issues/3, due to floating-point coordinates problem. Use https://github.com/sorayuki/VSFilterMod instead.
